---
title: "Tidy Tuesday - Week 5"
subtitle: "County-level American Community Survey (5-year estimates) 2015"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(geojsonio)
library(broom)
library(rgeos)
library(wesanderson)
library(ghibli)
library(ggthemes)
```

```{r}
df <- read.csv("acs2015_county_data.csv")
head(df)
str(df)
summary(df)
```

```{r}
df %>%
  ggplot(aes(x=Unemployment)) +
  geom_histogram(binwidth = 1)


```



```{r}
# From the excellent r-graph-gallery: https://www.r-graph-gallery.com/328-hexbin-map-of-the-usa/
spdf <- geojson_read("us_states_hexgrid.geojson.json",  what = "sp")

spdf@data = spdf@data %>% mutate(google_name = gsub(" \\(United States\\)", "", google_name))
spdf_fortified <- tidy(spdf, region = "google_name")
centers <- cbind.data.frame(data.frame(gCentroid(spdf, byid=TRUE), id=spdf@data$iso3166_2))
 
```


```{r}
acs2015_by_state <- df %>% group_by(State)

spdf_fortified = spdf_fortified %>%
  left_join(. , acs2015_by_state, by=c("id"="State")) 

head(spdf_fortified)
```


```{r fig.width=8, dpi=1200}

spdf_fortified$bin = cut(spdf_fortified$Unemployment , breaks=c(seq(0,15,1), Inf), labels=c(paste0(seq(0,14),"-",seq(1,15)),"15+"), include.lowest = TRUE)

pal <- wes_palette(16, name = "Moonrise2", type = "continuous")
pal2 <- wes_palette(16, name = "Darjeeling2", type = "continuous")
pal_alt <- tableau_seq_gradient_pal("Orange")(seq(0,1,length=16))

hex_plot <- ggplot() +
  geom_polygon(data = spdf_fortified, aes(fill = bin, x = long, y = lat, group = group) , size=0, alpha=0.9) +
  geom_text(data=centers, aes(x=x, y=y, label=id), color="white", size=3, alpha=0.6) +
  theme_void() +
  scale_fill_manual(values=pal, name="Unemployment rates %", guide = guide_legend( keyheight = unit(2, units = "mm"), 
                                                                                   keywidth=unit(9, units = "mm"), label.position = "bottom",
                                                                                   title.position = 'top', nrow=1 ) ) +
  labs(title = "Unemployment Rates By State", 
       subtitle = "2015 American Community Survey 5-year estimates",
       caption = "By @DaveBloom11 | Source: 2015 American Community Survey " ) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
    plot.subtitle = element_text(size= 12, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
    plot.caption = element_text(size = 8)
  )

hex_plot

ggsave("hexplot.jpg", dpi = 1200)
```



